<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>EvidenceCrafter</AssemblyName>
    <RootNamespace>EvidenceCrafter.App</RootNamespace>
    <Version>0.1.0-preview.30</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EvidenceCrafter.Core\EvidenceCrafter.Core.csproj" />
    <ProjectReference Include="..\EvidenceCrafter.Excel\EvidenceCrafter.Excel.csproj" />
  </ItemGroup>
</Project>
